//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NeuralNet.rc
//
#define IDD_ABOUTDLG                    100
#define IDR_MAINFRAME                   128
#define IDD_NETDLG                      129
#define IDS_NET_LAYER                   129
#define IDD_TRAININGDLG                 130
#define IDS_NET_PROMPT_EDIT             130
#define IDD_VECTORSDLG                  131
#define IDS_NETFILTER                   131
#define IDD_INFODLG                     132
#define IDS_ERROR_NET_HEADER            132
#define IDS_ERROR_OPEN                  133
#define IDD_IMPORTDLG                   134
#define IDS_ERROR_SAVE                  134
#define IDS_NETDEFEXT                   135
#define IDD_TEACHDLG                    136
#define IDS_NET_ERROR_IMAGE_SIZE        136
#define IDD_RECOGNIZEDLG                137
#define IDS_PROMPT_NET_SAVE             137
#define IDS_TRNFILTER                   138
#define IDD_TESTINGDLG                  138
#define IDS_TRNDEFEXT                   139
#define IDB_LOGO                        139
#define IDS_INFO_SIZE                   140
#define IDS_PROMPT_TRAINING_SAVE        141
#define IDS_INFO_ZERO                   142
#define IDS_INFO_NETZERO                143
#define IDS_IMPORT_FILTER               144
#define IDS_IMPORT_NO_OUTPUTS           145
#define IDS_IMPORT_NO_SELECTED_OUTPUT   146
#define IDS_ALL_VECTORS                 147
#define IDS_DELETE_VECTORS              148
#define IDS_DELETE_VECTOR               149
#define IDS_CLEAR_TRAINING              150
#define IDS_START_TRAINING              151
#define IDS_STOP_TRAINING               152
#define IDS_TEACH_VECTOR                153
#define IDS_LOG_TRAININGFILE            154
#define IDS_TEACH_START                 155
#define IDS_TEACH_VECTORS               156
#define IDS_TEACH_STOP                  157
#define IDS_TEACH_VECTOR_NAME           158
#define IDS_TEACH_EPOCH_NUMBER          159
#define IDS_TEACH_ERMS                  160
#define IDS_LOG_NETFILE                 161
#define IDS_LOG_NETTYPE                 162
#define IDS_LOG_NETINPUTS               163
#define IDS_LOG_NETOUTPUTS              164
#define IDS_LOG_NETLAYERS               165
#define IDS_LOG_TRAININGALGORITHM       166
#define IDS_LOG_TRAININGERROR           167
#define IDS_LOG_LAYERNEURONS            168
#define IDS_LOG_NETFUNCTION             169
#define IDS_LOG_CHANGEETA               170
#define IDS_LOG_CONSTETA                171
#define IDS_LOG_CHANGEALFA              172
#define IDS_LOG_CONSTALFA               173
#define IDS_LOG_EPOCHS                  174
#define IDS_LOG_REPEATS                 175
#define IDS_LOG_WIDTH                   176
#define IDS_LOG_HEIGHT                  177
#define IDS_LOG_MAXERMS                 178
#define IDS_TEACH_ONERMS                179
#define IDS_TEACH_EPOCH                 180
#define IDS_NET_OUTPUT                  181
#define IDS_RECOGNIZE_TEXT              182
#define IDS_RECOGNIZE_OUTPUT            183
#define IDS_NET_NOT_CREATED             184
#define IDS_TRAINING_NOT_CREATED        185
#define IDS_STRING186                   186
#define IDS_TRN_MUST_SAVE               186
#define IDC_TEACH_ALFA                  1000
#define IDC_BETA                        1001
#define IDC_TEACH_ETA                   1002
#define IDC_FUNCTION                    1003
#define IDC_NET_LAYERS                  1004
#define IDC_NET_ADD                     1005
#define IDC_NET_DEL                     1006
#define IDC_NET_INPUTS                  1009
#define IDC_NET_OUTPUTS                 1010
#define IDC_NET_INPUTS_SPIN             1011
#define IDC_NET_OUTPUTS_SPIN            1012
#define IDC_NET_LAYERS_SPIN             1013
#define IDC_NET_NEURONS                 1014
#define IDC_NET_NEURONS_SPIN            1015
#define IDC_TEST                        1016
#define IDC_CUT                         1017
#define IDC_DELETE_FILE                 1019
#define IDC_TRAINING_SETTINGS           1021
#define IDC_VECTORS_LIST                1022
#define IDC_CLEAR_TRAINING              1023
#define IDC_IMPORT_NAME                 1024
#define IDC_TEACH_LOGGER                1024
#define IDC_BREAKERMS                   1026
#define IDC_CONST_ALFA                  1032
#define IDC_CHANGE_ALFA                 1033
#define IDC_CONST_ETA                   1034
#define IDC_CHANGE_ETA                  1035
#define IDC_EPOCHS                      1036
#define IDC_INFO_LAYERS                 1037
#define IDC_END_ETA                     1038
#define IDC_END_ALFA                    1039
#define IDC_CHANGE_BETA                 1041
#define IDC_CHANGE_FUNCTION             1042
#define IDC_IMPORT_FILENAME             1045
#define IDC_IMPORT_BIAS                 1046
#define IDC_IMPORT_MONOCHROME           1047
#define IDC_IMPORT_GRAYED               1048
#define IDC_IMPORT_BLACK                1049
#define IDC_IMPORT_WHITE                1050
#define IDC_IMAGE                       1056
#define IDC_NET_WIDTH_SPIN              1057
#define IDC_NET_HEIGHT_SPIN             1058
#define IDC_WIDTH                       1059
#define IDC_HEIGHT                      1060
#define IDC_NET_PERCEPTRON              1061
#define IDC_NET_EBP                     1062
#define IDC_NET_QUADRA                  1063
#define IDC_NET_CATEGORIES              1064
#define IDC_NET_CATEGORY                1065
#define IDC_EPOCHS_SPIN                 1068
#define IDC_TEACH_PROGRESS              1073
#define IDC_IMPORT_OUTPUT               1081
#define IDC_VECTOR_NAME                 1082
#define IDC_MAXERMS                     1083
#define IDC_TEACH_ERMS                  1084
#define IDC_TEACH_STATUS                1086
#define IDC_LIST1                       1087
#define IDC_TEACH_EPOCH_STATUS          1087
#define IDC_LIST2                       1088
#define IDC_VECTOR_TESTING              1088
#define IDC_LIST3                       1089
#define IDC_WIDTH_SPIN                  1090
#define IDC_HEIGHT_SPIN                 1091
#define IDC_IMPORT_TESTING              1092
#define IDC_INFO                        1093
#define IDC_OUTPUTS_LIST                1094
#define IDC_OUTPUT_NAME                 1095
#define IDC_ADD_FILE                    1096
#define IDC_ADD_FOLDER                  1097
#define IDC_PASTE                       1098
#define IDC_TEACH_EPOCH_PROGRESS        1103
#define IDC_TEACH_TIME                  1104
#define IDC_REPEATS                     1105
#define IDC_SPIN1                       1107
#define IDC_TEACH_SHOWLOG               1109
#define IDC_RECOGNIZE_FILENAME          1110
#define IDC_BUTTON1                     1111
#define IDC_RECOGNIZE_IMAGE             1112
#define IDC_RECOGNIZE_OUTPUTS           1113
#define IDC_RECOGNIZE_TEXT              1114
#define IDC_RECOGNIZE_BROWSE            1115
#define IDC_IMPORT_IMAGE                1116
#define IDC_IMPORT_ALL                  1117
#define IDC_IMPORT_SKIP                 1118
#define IDC_IMPORT_OK                   1119
#define IDC_IMPORT_CANCEL               1120
#define IDC_INFO_INPUTS                 1121
#define IDC_INFO_OUTPUTS                1122
#define IDC_INFO_NEURONS                1123
#define IDC_INFO_HEIGHT                 1124
#define IDC_INFO_WIDTH                  1125
#define IDC_INFO_FUNCTION               1126
#define IDC_INFO_ALFA                   1127
#define IDC_INFO_BETA                   1128
#define IDC_INFO_ETA                    1129
#define IDC_NET_ETA                     1130
#define IDC_NET_ALFA                    1131
#define IDC_NET_BETA                    1132
#define IDC_NET_FUNCTION                1133
#define IDC_NET_WIDTH                   1134
#define IDC_NET_HEIGHT                  1135
#define IDC_NET_OK                      1136
#define IDC_NET_CANCEL                  1137
#define IDC_TEACH_MAXERMS               1138
#define IDC_TEACH_RANDOM                1139
#define IDC_RECOGNIZE_MONOCHROME        1140
#define IDC_RECOGNIZE_GRAYED            1141
#define IDC_RECOGNIZE_BIAS              1142
#define IDC_RECOGNIZE_BLACK             1143
#define IDC_RECOGNIZE_WHITE             1144
#define IDC_RECOGNIZE                   1145
#define IDC_RECOGNIZE_CLOSE             1146
#define IDC_TEACH_SHOWALL               1147
#define IDC_TEACH_OK                    1148
#define IDC_TEACH_CANCEL                1149
#define ID_TRAINING_EDIT                32780
#define ID_TRAINING_SAVE                32791
#define ID_TRAINING_OPEN                32792
#define ID_TRAINING_NEW                 32793
#define ID_NET_NEW                      32800
#define ID_NET_OPEN                     32802
#define ID_NET_SAVE                     32803
#define ID_NET_SAVE_AS                  32804
#define ID_NET_EDIT                     32805
#define ID_TRAINING_SAVE_AS             32806
#define ID_VECTORS_FOLDER               32820
#define ID_VECTORS_FILE                 32821
#define ID_VECTORS_LIST                 32822
#define ID_RECOGNIZE_RECOGNIZE          32826
#define ID_TESTING_TESTING              32827
#define ID_TRAINING_TEACH               32836
#define IDS_FORMAT_EPOCH                61203
#define IDS_FORMAT_EPOCHS               61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
